### ISSUE TITLE
Redirect welcome message from the bot

### ISSUE THREAD

**Issue by jedigeiss** [pcsg/steempunknet-discord-bot#13]
While this is a super idea in general, the welcome message currently (for new users) lands in the general channel of the steempunknet discord. This is killing off all the chat possibilities in there ;)
Tasks: Create a new channel for the welcoming in general and redirect the welcome message there.

**Comment by dehenne** [comment]
yes a little welcome in general, a big welcome then in the welcome.
But we also need to think about the Spanish text. :-/

**Comment by dehenne** [comment]
![image](https://user-images.githubusercontent.com/751811/36466738-e242818c-16db-11e8-8065-09cbb6a76c2f.png)

**Comment by dehenne** [comment]
![image](https://user-images.githubusercontent.com/751811/36466831-4d08dbe2-16dc-11e8-85a8-a1e6960dcb78.png)

![image](https://user-images.githubusercontent.com/751811/36466845-57afc8f8-16dc-11e8-90e2-2577792516c3.png)

![image](https://user-images.githubusercontent.com/751811/36466857-6125a646-16dc-11e8-80cb-9e024ae58856.png)

**Comment by dehenne** [comment]
![image](https://user-images.githubusercontent.com/751811/36467145-b71ded6e-16dd-11e8-8dcf-8a5d50d4e17d.png)
