### ISSUE TITLE
Show Player Rankings in the Discord

### ISSUE THREAD

**Issue by QUIQQER** [pcsg/steempunknet-discord-bot#5]
The Bot need some more Commands

- [x] `show top`
- [x] `show level*`
- [x] `show newest`
- [x] `show random` -> show a random player

**Comment by dehenne** [comment]
![image](https://user-images.githubusercontent.com/751811/36248071-7eae28dc-1236-11e8-9ef6-2a13f5563aa8.png)

**Comment by dehenne** [comment]
![image](https://user-images.githubusercontent.com/751811/36248080-88bce746-1236-11e8-9d7c-4a7ace43f285.png)

**Comment by dehenne** [comment]
![image](https://user-images.githubusercontent.com/751811/36293652-aaf3241a-12db-11e8-87d1-6136df2e62eb.png)
