### ISSUE TITLE
Suggestions for expand and improve the uses of the bot [STEEMPUNK-NET Discord Bot]

### ISSUE THREAD

**Issue by JillFeint** [pcsg/steempunknet-discord-bot#6]
My proposal consists of 4 suggestions

1- Add a field in the bot for the community in Spanish or other other communities in which you will be taught the command of the translation bot :t english or german text so you can interact with the whole community without difficulties.

2- Could the bot also leave a message in Spanish like the following, but with more fields added and corrections in the text:

### Sample:

Bienvenido a STEEMPUNK-NET @user.

La Corporación Ultima se complace en darle la bienvenida.

Como todos los luchadores nuevos, obtienes tu paquete de inicio el cual contiene algunos enlaces importantes como lo son los siguientes:

Complemento (Extensión) de Chrome para jugar a steempunk-net: https://chrome.google.com/webstore/detail/steempunk-net/jifcnginffjgcdcklciiodhaffgfbaph

Complemento (Extensión) de Firefox para jugar a steempunk-net: https://addons.mozilla.org/de/firefox/addon/steempunk-net/

Las preguntas frecuentes: https://www.steempunk.net/FAQ

Las preguntas frecuentes sobre la BETA: https://www.steempunk.net/FAQ/Beta-FAQ

Las estadísticas: https://www.steempunk.net/SPN/Stats

Los combatientes: https://www.steempunk.net/SPN/Fighters

El enlace más importante es la guía del juego hecha por @taitux donde se explica de forma detallada todo lo relacionado a Steempunk-net en español:

https://steemit.com/utopian-io/@taitux/guia-steempunk-net-el-primer-juego-mmorpg-en-steemit-smt-v1

The above could be an example to be used in different channels, but with different languages.

3- If it is not possible to add this in Spanish, at least add the last field in Spanish: "El enlace más importante es la guía del juego hecha por @taitux...."

4- For everyone the bot should leave a guide in English, because the guide for the Spanish community already add in the issues, that it can guide new users how to use Steempunk-net.

If you want to see my proposal better, I have created a publication in Utopian, you can go and see it, here is better explained.

https://utopian.io/utopian-io/@jillfeint/suggestions-for-expand-and-improve-the-uses-of-the-bot-steempunk-net-discord-bot

**Comment by dehenne** [comment]
![image](https://user-images.githubusercontent.com/751811/36350396-79a4c61c-1497-11e8-9312-2ce44ed62107.png)

**Comment by dehenne** [comment]
![image](https://user-images.githubusercontent.com/751811/36350620-cb5e909c-149b-11e8-96db-77729d8e1581.png)
