### ISSUE TITLE
feat: New help command

### ISSUE THREAD

**Issue by dehenne** [pcsg/steempunknet-discord-bot#8]
A help command must be implemented.
Some of the users have already requested
This should also be mentioned in the welcome text, too.

**Comment by QUIQQER** [comment]
![image](https://user-images.githubusercontent.com/25515268/36338383-cbf6a286-13ad-11e8-9e50-a410a87bafd5.png)

![image](https://user-images.githubusercontent.com/25515268/36338386-dc9a8bde-13ad-11e8-8e23-e46b0d5f88ba.png)
